### PR TITLE
Do not tweet in case of issue comment

### PR DESCRIPTION
**Pull request by Phu2**
Incorporate this change before setup a second instance on a fallback server.

### CODE REVIEW

**Comment by dr0i** [comment]
Don't know the context here - why this is needed?
Also, as we've migrated from twitter to mastodon - do we need this at all?

**Comment by Phu2** [comment]
I don't know either. Maybe @fsteeg can help?

**Comment by Phu2** [comment]
To clarify: this change was made on q1 already, but still not commited. 
In order to have this service in the same state on both servers, we should include it anyway?

**Comment by dr0i** [comment]
Ah, I see, the change was probably to reduce noise.
+1 for merging then.

**Review by dr0i — APPROVED** [review]

**Comment by fsteeg** [comment]
> Ah, I see, the change was probably to reduce noise.

Yes, if I remember correctly it was a request from @TobiasNx to have the Metafacture Twitter account tweet less.

**Comment by TobiasNx** [comment]
Yes it was about less noise in Twitter!

**Pull request merged**
